CREATE DATABASE QuanLyQuanAn_DB
GO
USE QuanLyQuanAn_DB
GO
CREATE TABLE TAIKHOAN (
	MANV INT NOT NULL,
	MATKHAU VARCHAR(20) NOT NULL,

	PRIMARY KEY (MANV)
)
GO
CREATE TABLE QUYEN (
	MAQUYEN INT NOT NULL,
	TENQUYEN NVARCHAR(50) NOT NULL,
	
	PRIMARY KEY (MAQUYEN)
)
CREATE TABLE PHIEUNHAP (
	MAPHIEU INT NOT NULL,
	NGAYNHAP DATETIME,

	PRIMARY KEY (MAPHIEU)
)
GO
CREATE TABLE CHITIETPHIEUNHAP (
	MAPHIEU INT NOT NULL, 
	MANVL INT NOT NULL,
	SOLUONG INT NOT NULL,

	PRIMARY KEY (MAPHIEU, MANVL)
)
GO
CREATE TABLE LOAIMONAN (
	MALOAIMA INT NOT NULL,
	TENLOAIMA NVARCHAR(50),
	NGUNGKINHDOANH BIT

	PRIMARY KEY (MALOAIMA)
)
GO
CREATE TABLE MONAN (
	MAMA INT NOT NULL,
	MALOAIMA INT NOT NULL,
	TENMA NVARCHAR(200),
	DVT NVARCHAR(20),
	SOLUONG INT,
	DONGIABAN DECIMAL,
	HINHANH IMAGE,
	KHUYENMAI INT,
	NGUNGKINHDOANH BIT

	PRIMARY KEY (MAMA)
)
GO
CREATE TABLE LOAINHANVIEN (
	MALOAI INT NOT NULL,
	TENLOAI NVARCHAR(50)

	PRIMARY KEY (MALOAI)
)
GO
CREATE TABLE NHANVIEN (
	MANV INT NOT NULL,
	MALOAI INT NOT NULL,
	MAQUYEN INT NOT NULL,
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(100),
	SDT VARCHAR(20),
	EMAIL VARCHAR(20),
	GIOITINH BIT,
	NGAYSINH DATETIME,
	HINHANH IMAGE,
	DATHOIVIEC BIT,


	PRIMARY KEY (MANV)
)
GO
CREATE TABLE KHACHHANG (
	MAKH INT NOT NULL,
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(100),
	SDT VARCHAR(20),
	EMAIL VARCHAR(20),
	GIOITINH BIT,
	NGAYDK DATETIME,
	DOANHSO DECIMAL,
	DAXOA BIT

	PRIMARY KEY (MAKH)
)
GO
CREATE TABLE HOADON (
	SOHD INT NOT NULL,
	MANV INT NOT NULL,
	SOBAN INT NOT NULL,
	NGAYLAP DATETIME,
	MAKH INT,
	DATHANHTOAN BIT,
	TIENKHACHHANGTRA DECIMAL,

	PRIMARY KEY (SOHD)
)
GO
CREATE TABLE BAN
(
	SOBAN INT NOT NULL,
	TRANGTHAI BIT
	
	PRIMARY KEY (SOBAN)
)
GO
CREATE TABLE CTHD (
	SOHD INT NOT NULL,
	MAMA INT NOT NULL,
	SOLUONG INT,
	
	PRIMARY KEY (SOHD, MAMA)
)
GO
CREATE TABLE NGUYENVATLIEU (
	MANVL INT NOT NULL,
	TENNVL NVARCHAR(50),
	DVT NVARCHAR(20),
	NGAYMUA DATETIME,
	NGAYHETHAN DATETIME,
	SOLUONG INT,
	DONGIAMUA DECIMAL

	PRIMARY KEY (MANVL)
)
GO
CREATE TABLE CHEBIEN
(
	MANVL INT NOT NULL,
	MAMA INT NOT NULL,
	SOLUONG INT
	PRIMARY KEY(MANVL, MAMA)
)
GO
ALTER TABLE CHEBIEN ADD
CONSTRAINT FK_CHEBIEN_NVL FOREIGN KEY (MANVL) REFERENCES NGUYENVATLIEU(MANVL)
GO
ALTER TABLE CHEBIEN ADD
CONSTRAINT FK_CHEBIEN_MONAN FOREIGN KEY (MAMA) REFERENCES MONAN(MAMA)
GO
ALTER TABLE TAIKHOAN 
ADD CONSTRAINT FK_TK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE CHITIETPHIEUNHAP
ADD CONSTRAINT FK_CTPN_MAPHIEU FOREIGN KEY (MAPHIEU) REFERENCES PHIEUNHAP(MAPHIEU)
GO
ALTER TABLE CHITIETPHIEUNHAP
ADD CONSTRAINT FK_CTPN_MANVL FOREIGN KEY (MANVL) REFERENCES NGUYENVATLIEU(MANVL)
GO
ALTER TABLE MONAN
ADD CONSTRAINT FK_MA_MALOAIMA FOREIGN KEY (MALOAIMA) REFERENCES LOAIMONAN(MALOAIMA)
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_MALOAI FOREIGN KEY (MALOAI) REFERENCES LOAINHANVIEN(MALOAI)
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_MAQUYEN FOREIGN KEY (MAQUYEN) REFERENCES QUYEN(MAQUYEN)
GO
ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
GO
ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_SOBAN FOREIGN KEY (SOBAN) REFERENCES BAN(SOBAN)
GO
ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
GO
ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_MAMA FOREIGN KEY (MAMA) REFERENCES MONAN(MAMA)